language: objective-c
osx_image: xcode10
env:
  global:
  - WORKSPACE="TSegmentedView.xcworkspace"
  - FRAMEWORK_SCHEME="TSegmentedView"
  - EXAMPLE_SCHEME="Example"
  matrix:
    - DESTINATION="OS=11.0,name=iPhone X"          SCHEME="$FRAMEWORK_SCHEME"   BUILD_EXAMPLE="YES"   POD_LINT="YES"
    - DESTINATION="OS=10.3.1,name=iPhone 7 Plus"   SCHEME="$FRAMEWORK_SCHEME"   BUILD_EXAMPLE="YES"   POD_LINT="NO"
    - DESTINATION="OS=9.3,name=iPhone 6"           SCHEME="$FRAMEWORK_SCHEME"   BUILD_EXAMPLE="YES"   POD_LINT="NO"
    - DESTINATION="OS=8.1,name=iPhone 5s"          SCHEME="$FRAMEWORK_SCHEME"   BUILD_EXAMPLE="YES"   POD_LINT="NO"

before_install:
  - gem install cocoapods
  - pod repo update
  - pod install

script:
  - env
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcpretty --version

  # Build Framework in Debug and Run Tests if specified
  - xcodebuild clean build -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" | xcpretty

  # Build Example in Debug if specified
  - if [ $BUILD_EXAMPLE == "YES" ]; then
      xcodebuild clean build -workspace "$WORKSPACE" -scheme "$EXAMPLE_SCHEME" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO | xcpretty;
    fi

  # Run `pod lib lint` if specified
  - if [ $POD_LINT == "YES" ]; then
      pod lib lint;
    fi

    